#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

base_address: https://donate.ukremb.at

#REQUIRED
org_site_title: "#nextstopvictory"
org_site_title_second: "#standwithukraine"
org_name: "Botschaft der Ukraine in der Republik Österreich"
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.

org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.


#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: wien.embassy.ua@gmail.com
org_street_address: Naaffgasse 23 #Please include suite number on the line below
org_address_suite:
org_city: Wien
org_state:
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  1180
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  +43 1 479 7172

#SOCIAL MEDIA
org_twitter_username:
org_facebook_username: ukremb.at
org_instagram_username:

org_main_website_address: https://austria.mfa.gov.ua

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: false

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: false
tinyletter_username: false

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: one

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: test
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0

paypal_success_message: "Thank you for your donation! That's means so much for us."
paypal_cancel_message: "Thank you! May be next time."
paypal_error_message: "Some error are happens! Please, try again later."
